# Generated by Django 2.2.5 on 2021-12-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choices_type',
            field=models.IntegerField(choices=[(1, '用户'), (2, 'VIP用户'), (3, '管理员')], default=2),
        ),
    ]
