# Generated by Django 2.2.5 on 2022-01-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_user_choices_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choices_type',
            field=models.IntegerField(choices=[(1, '用户'), (2, 'VIP用户'), (3, '管理员')], default=1),
        ),
    ]
