# Generated by Django 2.2.5 on 2022-01-04 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='活动名称')),
                ('activity_start_date', models.TimeField(default=django.utils.timezone.now, verbose_name='活动开始日期')),
                ('activity_end_date', models.TimeField(auto_now=True, verbose_name='获得结束日期')),
                ('demo', models.TextField()),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'db_activity',
            },
        ),
        migrations.CreateModel(
            name='Win_Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.TimeField(default=django.utils.timezone.now)),
                ('updata_date', models.TimeField(auto_now=True)),
                ('demo', models.CharField(max_length=200, verbose_name='备注')),
                ('state', models.IntegerField(blank=True, choices=[(1, '发货'), (2, '下单'), (3, '签收'), (4, '未签收'), (5, '运输')], default=2, null=True)),
                ('prize_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='中奖的用户')),
                ('win_prize_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Activity', verbose_name='属于那个活动')),
            ],
            options={
                'verbose_name': '用户中奖详细表',
                'verbose_name_plural': '用户中奖详细表',
                'db_table': 'db_user_win_prize',
            },
        ),
        migrations.CreateModel(
            name='Prize_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='奖的名称')),
                ('create_date', models.TimeField(default=django.utils.timezone.now)),
                ('update_date', models.TimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Activity', verbose_name='奖所属的活动')),
            ],
            options={
                'verbose_name': '奖分类',
                'verbose_name_plural': '奖分类',
                'db_table': 'db_prize_type',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='奖品名称')),
                ('money', models.CharField(max_length=20, verbose_name='价格')),
                ('demo', models.TextField()),
                ('prize_win_prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Prize_type')),
            ],
            options={
                'verbose_name': '奖品表',
                'verbose_name_plural': '奖品表',
                'db_table': 'db_prize',
            },
        ),
    ]
