# Generated by Django 2.2.5 on 2022-01-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_win_prize_prize_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='demo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prize',
            name='money',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='价格'),
        ),
    ]
