# Generated by Django 2.2.5 on 2022-01-08 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lotteryrecord_luckdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckdraw',
            name='create_date',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='穿件时间'),
        ),
    ]
