# Generated by Django 2.2.5 on 2022-01-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220108_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luckdraw',
            name='luckdraw_prize_type',
        ),
    ]
