# Generated by Django 2.2.5 on 2022-01-14 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_remove_luckdraw_luckdraw_prize_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotteryrecord',
            options={'verbose_name': '抽奖记录', 'verbose_name_plural': '抽奖记录'},
        ),
        migrations.AddField(
            model_name='lotteryrecord',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='lotteryrecord',
            name='demo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lotteryrecord',
            name='lotteryrecord_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Activity'),
        ),
        migrations.AddField(
            model_name='lotteryrecord',
            name='lotteryrecord_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotteryrecord',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='win_prize',
            name='prize_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Prize_type', verbose_name='中奖等级名称'),
        ),
        migrations.AlterField(
            model_name='win_prize',
            name='state',
            field=models.IntegerField(choices=[(1, '发货'), (2, '下单'), (3, '签收'), (4, '未签收'), (5, '运输')], default=2),
        ),
        migrations.AlterModelTable(
            name='lotteryrecord',
            table='db_lotteryrecord',
        ),
    ]
